### ISSUE TITLE
Error in clicking participant list in line 58 

### ISSUE THREAD

**Issue by harshraj6982** [Titan1911/Google-Meet-Attendance-using-Python#1]
Here I am geeting Error. Please Resolve this issue asap.

Traceback (most recent call last):
  File "C:\Users\HARSH\AppData\Local\Programs\Python\Python38\Attendence.py", line 58, in <module>
    driver.find_element_by_css_selector('div.uArJ5e.UQuaGc.kCyAyd.QU4Gid.foXzLb.IeuGXd').click()  # participant list
  File "C:\Users\HARSH\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\HARSH\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\HARSH\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HARSH\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.uArJ5e.UQuaGc.kCyAyd.QU4Gid.foXzLb.IeuGXd"}
  (Session info: chrome=85.0.4183.121)

**Comment by harshraj6982** [comment]
This error occurred due to slow internet connection. Increase time.sleep to 5-6 seconds  in order to resolve the issue if your internet speed is slow.
