### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by devilminati** [Titan1911/Google-Meet-Attendance-using-Python#2]
It works like charm till it reaches meet.google.com after that it doesn't join the meetings or anything.

Logs:
Traceback (most recent call last):
  File "Attendance.py", line 60, in <module>
    driver.find_element_by_css_selector('div.uArJ5e.UQuaGc.Y5sE8d.uyXBBb.xKiqt').click()  # join now
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=86.0.4240.75)

E:\Google-Meet-Attendance-using-Python>[8576:19304:20201013,142649.092:ERROR crash_report_database_win.cc:609] CreateDirectory : The system cannot find the path specified. (3)
Could not initialize crash reporting DB
Can not init crashpad with status: CRASHPAD_DB_INIT_ERROR

**Comment by Titan1911** [comment]
Try increasing the `sleep()` function argument to, say `4`, in line 48 and 59. Hope it works!
